### ISSUE TITLE
Graph-node：RPC error: Error { code: InvalidParams, message: "invalid argument 1: hex string without 0x prefix", data: None }

### ISSUE THREAD

**Issue by SentDz** [okx/exchain#813]
### 1. Describe

I tried to deploy graph to obtain swap data, but an error occurred when creating a trading pair
The error log is as follows:

Ethereum node returned an error when calling function "name" of contract "ERC20": RPC error: Error { code: InvalidParams, message: "invalid argument 1: hex string without 0x prefix", data: None }

The same code runs normally in eth/heco after changing the network

## Steps to Reproduce

1.fork any swap-subgraph
2.change the network and run it
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SentDz** [comment]
According to the log, it seems to occur when any field of the token is obtained when the transaction pair is created (symbol,name....)

**Comment by KamiD** [comment]
plz use v0.18.3 to test again, the problem should be resolved

**Comment by linxux** [comment]
Meet the same issue,
```
graph-node_1  | Jul 19 13:34:02.646 DEBG Trying again after eth_call RPC call failed (attempt #1) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "invalid argument 1: hex string without 0x prefix", data: None }))), ...
```
And `web3_clientVersion`,
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "exchain-v0.18.9"
}
```

**Comment by xiaoxuez** [comment]
> plz use v0.18.3 to test again, the problem should be resolved


Hi, I meet the same error. change exchaind to v0.18.3, also not work, would you provide more messages about graph-node version?

**Comment by xiaoxuez** [comment]
I change graph-node to v0.19.2， It works

**Comment by linxux** [comment]
Hi @xiaoxuez , I had change the `graph-node` version to `v0.19.2`.
But still get the same issue. Do you have change other code on the `graph-node`?

**Comment by xiaoxuez** [comment]
> Hi @xiaoxuez , I had change the `graph-node` version to `v0.19.2`.
> But still get the same issue. Do you have change other code on the `graph-node`?

add config `GRAPH_ETH_CALL_BY_NUMBER: true`

**Comment by banishee** [comment]
https://forum.okt.club/d/180-oecthegraph
There is a simple way of building graph-node, have a try
